# Generated by Django 2.2.2 on 2021-03-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='文件名')),
                ('files', models.FileField(max_length=128, upload_to='', verbose_name='文件')),
            ],
        ),
    ]
